const BEE_NODE_URL = 'BEE_NODE_URL';
const GNOSIS_BLOCKTIME_IN_SECONDS = 5;

const MINIMUM_POSTAGE_STAMPS_DEPTH = 21;
const UNIT_OF_CHUNK = 4 * 1024; // 4kb

export {
  BEE_NODE_URL,
  UNIT_OF_CHUNK,
  MINIMUM_POSTAGE_STAMPS_DEPTH,
  GNOSIS_BLOCKTIME_IN_SECONDS,
};